### ISSUE TITLE
Sign up & Login account management

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#16]
## User Story
As a user, I want to be able to create a new account and log in

## Detailed Description
We need to provide the frontend and backend capabilities to create a new account or login to an existing one. 
The frontend should resemble a form. For the backend, a secure hashing algorithm, secure string compare function & session tokenization capabilities to hash & check passwords, and issue tokens respectively.

## Subtasks (Please also link task PRs here)
- [x] Add backend auth routes (passport) #29 
- [x] Add frontend forms & test that it is working
- [x] Create sequence diagrams to explain auth flow (4 entities: User, Backend, database, Session store)  @SeunghyunDKim

**Comment by willyspinner** [comment]
UPDATE: due to urgency on deploying the auth routes, we have deployed the backend part first in #29 . 

Now, it is up to @lorance19  to finish the frontend implementations

**Comment by willyspinner** [comment]
@SeunghyunDKim  I assigned you another task to create sequence diagrams for the auth flow (see above).

**Comment by willyspinner** [comment]
Login feature merged (Backend & frontend) and sequence diagrams done, so this'll be closed.
