### ISSUE TITLE
Epic: Portfolio and trading 

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#2]
## Epic

The Users should be able to buy or sell stocks during market hours, and see the history of their trades

In addition to the buy/sell feature, the user will save the bought stocks into a portfolio of active investments. 

## User Stories
- [x] #20 (maintain portfolio of stocks)
- [x] #14 (buy and sell stocks during market hours)
- [x] #15 (use realtime stock price to trade)
- [x] #17 (history of trades)
- [x] #45 (watchlist & portfolio on chart page)
- [x] #46 (portfolio growth over time)

**Comment by willyspinner** [comment]
Donezo
