### ISSUE TITLE
Epic: Live market data 

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#3]
## Epic
Users are able to browse through stock charts of different tickers, and obtain **up-to-date** data at various intervals such as intraday (hourly), daily, weekly, monthly, yearly, etc.

There are two parts to this epic, the frontend charting UI and the backend realtime API that feeds live stock data to the end user.

## User Stories
- [x] story #12  (basic chart to view stocks)
- [x] story #13 (live data feed for stock chart) 
- [x] story #21 (portfolio updated realtime)
- [x] story #43  (able to search for stocks)
