### ISSUE TITLE
 integration testing set up 

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#31]
## User Story
As a developer, I want to have integration testing set up so that future feature stories can have integration testing.

## Detailed Description
We need to do a few things here:
- Travis CI can provision a test postgresql database (see [here](https://docs.travis-ci.com/user/database-setup/)) to be used in our build. We can connect to this databsae while doing integration testing to make sure our queries & request response logic work on top of the existing unit tests.
- We need to write the actual integration tests of the format: Hit an endpoint e.g. `/api/trading/buy` and expect a JSON response. Don't stub anything, and set `PG_CONNSTR` accordingly so that we can connect to the database.

## Subtasks (Please also link task PRs here)
- [x] Create integration testing infra setup on travis  @willyspinner 
- [x] Create integration tests for trading routes  @willyspinner 
- [ ] Create integration tests for account routes  @varun1729  
^ these can just be done in one PR. Easier that way.
