### ISSUE TITLE
Epic: Project set-up

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#4]
## Epic
To do a one-time set up of a mature, productionized project so that we can be up and running. We need to setup the project structure (how backend and frontend folders are laid out, how does the backend serve the frontend, etc.), basic dependencies, gitignores.

Then, we need to provision our cloud infrastructure for the project. We chose Elastic Beanstalk and RDS for our App and Database provisioning respectively. These must be setup and ready so that CICD can run smoothly. 

## User Stories
- [x] story #5 (cicd pipeline)
- [x] story #6 (frontend & backend skeleton setup)
- [x] story #7 (cloud environment setup)
- [x] story #40  (apidoc generation)

**Comment by willyspinner** [comment]
This epic is now Done!

**Comment by willyspinner** [comment]
Opening since we need to set up integration testing

**Comment by willyspinner** [comment]
STory #41 is not our priority right now, we should be doing it at the end. ADding codecov in a native-ES6 node environment is a bit hard mainly because standard code cov tools like `istanbul.js` bind to ES5 statements like `require()`, whereas we use `import`.

**Comment by willyspinner** [comment]
UPDATE: moving codecov and testing stories to a new epic #55  for testing - since it is out of scope for the original 'project setup'.

 Since all stories here are done, we are closing this.
