### ISSUE TITLE
add Watchlist + portfolio on chart page

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#45]
## User Story
As a user, I would like to have my watchlist and portfolio handy when looking / buying stocks in chart page.

## Detailed Description
As discussed, we want to put the watchlist and portfolio in the same place at the chart page, which is directly below the stock chart.

We also need to show the balance of remaining funds and stocks owned in the chart page (in the buy and sell widget or below it - TBD).

There will be a frontend and backend component for this:
- Backend needs to implement the watchlist (like) feature for each stock - Get, add and remove. 
- Frontend will need to create a tabbed view that has an option to select watchlist or portfolio in chart page.

## Subtasks (Please also link task PRs here)
All will be done in 1 PR
- [x] Backend - Add temporary portfolio value for each item (hardcoded)
- [x] Backend - Add PG table for watchlist
- [x] Backend - Add watchlist routes (Get, Add & Remove)
- [x] Frontend - create watchlist component with watchlist service
- [x] Frontend - add tab to navigate between portfolio & watchlist in chart page

**Comment by willyspinner** [comment]
Works now, needs to be reviewed and merged
<img width="1148" alt="Screen Shot 2021-02-16 at 3 30 12 AM" src="https://user-images.githubusercontent.com/17305586/108109138-5d48b600-7046-11eb-8a92-1ed5f32abcc2.png">
