### ISSUE TITLE
Epic: Testing

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#55]
## Epic
It is important to have a majority of our code tested for any scenario it'll receive, so that we don't get any unexpected bugs.

We want our frontend and backend code fully tested - unit and integration. Also, we need to add code coverage so that we know how much of our code is tested.

## User Stories
- [x] story #31 (Integration testing set up)
- [x] story #54 (Frontend tests) 
- [x] story #41 (add code coverage)

**Comment by willyspinner** [comment]
Closing this since it is done.
